spring:
  profiles:
    active: dev
  arangodb:
    host: 127.0.0.1
    port: 8529
    timeout: 1000
    user: admin
    password: admin
    userSsl: false
    repositoryPackage: com.zgh.arangodemo
    namedQueriesLocation: classpath:/arango/*.properties
server:
  port: 8080